### ISSUE TITLE
document is not defined !!

### ISSUE THREAD

**Issue by rakibulalam** [inferusvv/react-odometerjs#12]
When trying to render your component. It's showing the error in odometer js file that document is not defined !!

**Comment by bezenson** [comment]
Could you provide more info? How you integrate it?

**Comment by bezenson** [comment]
I've upgraded library today. Please try with new version

**Comment by rakibulalam** [comment]
Server-side rendering showing the error. I will test it again. I will keep the error status.

**Comment by bezenson** [comment]
@rakibulalam Server side rendering is not supported. Odometer.js is front-end library

**Comment by rakibulalam** [comment]
Thanks, I understand and need to skip the server rendering.
