### ISSUE TITLE
How do you resize it?

### ISSUE THREAD

**Issue by bestwestern** [inferusvv/react-odometerjs#14]
the odometer docs says:
![image](https://user-images.githubusercontent.com/3617433/50178275-58700680-0304-11e9-96e0-103842331ae5.png)
but this doesn't work:
![image](https://user-images.githubusercontent.com/3617433/50178355-8e14ef80-0304-11e9-9eb5-da5d5ac05925.png)

**Comment by bezenson** [comment]
Now props not passing to wrapper 'div' ([code](https://github.com/inferusvv/react-odometerjs/blob/master/src/index.js#L39)). But you can make pull request for that, or I'll do it later.

As a workaround try to use CSS for that and not use inline style

**Comment by fapjsc** [comment]
any update?

**Comment by bezenson** [comment]
Added support for `style` prop and all other `div` props. Please check v3.1.0
