### ISSUE TITLE
how can i use toLocaleString....??? 

### ISSUE THREAD

**Issue by MuttakinHasib** [inferusvv/react-odometerjs#16]

**Comment by MuttakinHasib** [comment]
also when i pass value as a props from App.js (class component) to Card.js (functional component) 

it's not working (animating)

![Screenshot_8](https://user-images.githubusercontent.com/44552983/79530387-09cf9b00-8024-11ea-920b-babefd402c22.png)
![Screenshot_9](https://user-images.githubusercontent.com/44552983/79530404-13f19980-8024-11ea-9f2b-33fda7de2291.png)

**Comment by bezenson** [comment]
@MuttakinHasib Could you create reproducible demo on https://codesandbox.io/ for example?

**Comment by MuttakinHasib** [comment]
https://github.com/MuttakinHasib/react-covid.git

#live : https://react-covid.now.sh/

**Comment by MuttakinHasib** [comment]
i used countup but i want to use odometerjs
