### ISSUE TITLE
Need a better example...

### ISSUE THREAD

**Issue by merriam** [inferusvv/react-odometerjs#19]
It would be good to have a slightly better example, for example, as found at https://medium.com/@PostgradExpat/create-an-animated-counter-with-react-odometerjs-hubspot-odometer-js-2f32eb103709

That is, an example should show importing a theme.  Let me know if you want me to provide one.

**Comment by bezenson** [comment]
Hello! Yes, if you have ability - please create pull request with example

**Comment by bezenson** [comment]
I've updated Readme. Hope it's enough. Closing issue
