### ISSUE TITLE
format not working as expected - or perhaps I am dumb

### ISSUE THREAD

**Issue by sidestepper** [inferusvv/react-odometerjs#20]
I am using version 2.1.0 with react 16.4.1 (If this helps to identify, I can also specify other packages in use).

I am trying to add an odometer to our page reflecting money. I can't seem to get the '$'-sign in front of the number(This is not major, and no biggie if it can't really be done).

My main issue is when I attempt to use format (,ddd).dd, I am still not getting the last d when it is 0.

```
this.setState({ theMoney: 17.60 });

...

<Odometer value={this.state.theMoney} duration={1000} format='(,ddd).dd'/>
```

Above results in the odometer still showing "17.6"

I have attempted converting _theMoney_ to a string but, as expected, it is converting back to a number under the hood, so the last 0 still gets lost.

Is this a known issue, or am I just doing something wrong? I admit I am in an unfamiliar codebase, and have not used odometer before, so it is possible I am just doing something dumb, or missed something in documentation somewhere.

Thanks in advance for any assistance.

**Comment by bezenson** [comment]
I've checked this and can confirm, that original Odometer.js library have this bug. I need to think about switching to maintained fork described here https://github.com/inferusvv/react-odometerjs/issues/17

**Comment by bezenson** [comment]
I am going to close this issue as it is duplicate

**Comment by UntappedSolutions** [comment]
@inferusvv Did you ever find a solution to the format bug? No worries if not I just wanted to check. I am working on a css solution at the moment

**Comment by bezenson** [comment]
Seems to be need to move to fork or copy original library here and fix. I'll try to do that soon.

**Comment by UntappedSolutions** [comment]
its hacky and horrible but I just achieved it with this:
        .odometer-inside span:nth-of-type(2){
          display: none;
        }
        span.odometer-digit-inner{
          display:block !important;
        }
        span.odometer-digit{
          display:inline-block !important;
        }

**Comment by UntappedSolutions** [comment]
thank you for quick response, very much appreciated
