### ISSUE TITLE
Getting 8 in front of each numbers.

### ISSUE THREAD

**Issue by Madeindreams** [inferusvv/react-odometerjs#43]
Not sure why. The Odometer module was working fine and then it broke.

`<Odometer value={1234} format="(,ddd).dd" />`

output

81,828384

Anyone know why?

**Comment by MunnyReol** [comment]
> Not sure why. The Odometer module was working fine and then it broke.
> 
> `<Odometer value={1234} format="(,ddd).dd" />`
> 
> output
> 
> 81,828384
> 
> Anyone know why?

I think,
It's because of css. You may not import css ?

**Comment by bezenson** [comment]
Exactly. Please check CSS. This "8"s generated by original library

**Comment by Madeindreams** [comment]
Yes that was it!

**Comment by Saky96** [comment]
I am getting the same issue, and I have imported the css as given in the documentation in my index.html
`<link rel="stylesheet" href="odometer-theme-default.css" />`
Still i get this error and css is not getting applied in my project.
Anything i might have done right?

**Comment by MunnyReol** [comment]
> 

open the page url by putting view-source: before the url like, `view-source:https://domain.com`    and then click on href link `<link rel="stylesheet" href="odometer-theme-default.css" />`
Check, if the href css file location is correct or not

**Comment by bezenson** [comment]
Correctly. You should download theme CSS file and put somewhere in project. Then import it.

Do you think I should update Readme to make it more clear for everyone?

**Comment by MunnyReol** [comment]
> 

It will be good.

And i have a question.
Is it possible to make this odometer for react native.
I need odometer for in react native but i have not find any library of odometer for react native..

**Comment by bezenson** [comment]
> Is it possible to make this odometer for react native.

Unfortunately no. This is just a wrapper over odometer.js for web.

**Comment by Saky96** [comment]
> Correctly. You should download theme CSS file and put somewhere in project. Then import it.
> 
> Do you think I should update Readme to make it more clear for everyone?

Thanks, that worked!
Yes, I think you can update the Readme, as it will be more precise and someone like me wouldn't get stuck.
