### ISSUE TITLE
Could not find a declaration file for module 'react-odometerjs'

### ISSUE THREAD

**Issue by willisIT** [inferusvv/react-odometerjs#44]
error An unexpected error occurred: "https://registry.npmjs.org/@types%2freact-odometerjs: Not found".

**Comment by Ashish-BeCodie** [comment]
There is a lot of packages that are not typescript packages, so to fix this error just change compilerOptions.strict to false in tsconfig

ref - https://stackoverflow.com/questions/45382951/where-should-i-place-custom-d-ts-files

**Comment by bezenson** [comment]
Hey! New version v3 comes with typescript :)
