### ISSUE TITLE
Getting Wrong Value 😓

### ISSUE THREAD

**Issue by SouZe-San** [inferusvv/react-odometerjs#49]
give value=1000
getting - 8108080

![image](https://github.com/user-attachments/assets/2c9a8bd4-50c5-4594-bf38-a4943f886af1)

**Comment by zacharytomlinson** [comment]
Same issue.

**Comment by zacharytomlinson** [comment]
Import CSS file in your app <head>: `<link rel="stylesheet" href="odometer-theme-default.css" />`

**Comment by bezenson** [comment]
Yes, you didn't apply CSS. Closing issue
