### ISSUE TITLE
Unexpected behavior using create-react-app 

### ISSUE THREAD

**Issue by richieio** [inferusvv/react-odometerjs#6]
Hi, very much looking forward to using this library. But I tried just a demo in create-react-app and the output did not match what I was expecting. The value I entered is `1234` and the output I received was `81,828384`!

![screen shot 2017-07-26 at 12 00 40 pm](https://user-images.githubusercontent.com/755288/28631182-5e2e62a2-71fa-11e7-9e69-657b242a7c29.png)

My `App.js` file in a fresh create-react-app. I copied the options from the odometer docs. Even without it, the value is way off. 

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import Odometer from 'react-odometerjs';

class App extends Component {
  render() {
    return (
      <div className="App">
        <Odometer
          value={1234}
          format="(,ddd).dd"
          options={{
            auto: false, // Don't automatically initialize everything with class 'odometer'
            selector: '.my-numbers', // Change the selector used to automatically find things to be animated
            format: '(,ddd).dd', // Change how digit groups are formatted, and how many digits are shown after the decimal point
            duration: 3000, // Change how long the javascript expects the CSS animation to take
            theme: 'car', // Specify the theme (if you have more than one theme css file on the page)
            animation: 'count'
          }}
        />
      </div>
    );
  }
}

export default App;

```

Any idea what's going on here? I'm lost.

Thanks!

Rich

**Comment by richieio** [comment]
Further investigation reveals an `8` in between each digit of the value in it's `odometer-digit-spacer` span. Strangely, this seems to be expected behavior of the hubspot odometer without React.

By adding `import 'odometer/themes/odometer-theme-car.css';` to my example app, it hides this 8 span digit in my value and appears to work as expected. Perhaps the "theme" option doesn't seem to work, and thus a user would need to add the theme css directly.

![screen shot 2017-07-26 at 12 42 21 pm](https://user-images.githubusercontent.com/755288/28632874-eb8a75e6-71ff-11e7-9eee-799821617c85.png)

Cheers

**Comment by bezenson** [comment]
Yes, this is behavior of Odometer.js. This repo is just a React wrapper. Styling is up to you.
