### ISSUE TITLE
8 symbol in value

### ISSUE THREAD

**Issue by Rudnev90** [inferusvv/react-odometerjs#8]
<img width="411" alt="2018-02-08 15 01 51" src="https://user-images.githubusercontent.com/15821454/35971980-0c0104a8-0ce1-11e8-9146-f536111590e4.png">
Why he's add symbol 8?

Oh, i find it 
<img width="1275" alt="2018-02-08 15 15 29" src="https://user-images.githubusercontent.com/15821454/35972793-4c992a92-0ce4-11e8-8b2d-20b46b1c7a16.png">
it's from to odometer.js

in version 1.0.1 all fine, bun version 2.0.0 has bug
Thats it, i can't use it, cuz react 15.6.2 deps, but i use 16.2.0

**Comment by ptcampbell** [comment]
You need to include the stylesheet.

**Comment by bezenson** [comment]
I'll make react as a peer dependency soon

**Comment by bezenson** [comment]
React upgraded and moved to peerDependencies. All should be fine now
